# Generated by Django 6.0 on 2025-12-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.TextField(help_text='Resumo para a Home')),
                ('conteudo', models.TextField(help_text='Conteúdo completo da página')),
                ('icone', models.CharField(default='star', help_text='Nome do ícone (Lucide/Heroicons)', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Atuação',
                'verbose_name_plural': 'Atuações',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('linkedin', models.URLField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Equipe',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('capa', models.ImageField(upload_to='blog/')),
                ('resumo', models.TextField()),
                ('conteudo', models.TextField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('destaque', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Blog',
                'ordering': ['-publicado_em'],
            },
        ),
    ]
