# Generated by Django 6.0 on 2026-01-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text='Use HTML básico se precisar, ex: <br> para quebrar linha.')),
                ('subtitulo', models.TextField()),
                ('texto_botao', models.CharField(default='Conhecer áreas de atuação', max_length=50)),
                ('link_botao', models.CharField(default='/atuacoes', max_length=200)),
                ('imagem_fundo', models.ImageField(help_text='Recomendado: 1920x1080px', upload_to='hero/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner da Home',
                'verbose_name_plural': 'Banners da Home',
            },
        ),
    ]
