# Generated by Django 6.0 on 2026-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_herohome'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Um escritório humano...', max_length=200)),
                ('texto', models.TextField(help_text='Texto completo da descrição.')),
                ('imagem_fundo', models.ImageField(help_text='Imagem menor (Fundo). Ideal: 263x283px', upload_to='quem_somos/')),
                ('imagem_frente', models.ImageField(help_text='Imagem maior (Frente). Ideal: 450x290px', upload_to='quem_somos/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seção Quem Somos',
                'verbose_name_plural': 'Seção Quem Somos',
            },
        ),
    ]
