# Generated by Django 6.0 on 2026-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_quemsomos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (ex: 1, 2, 3)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais',
                'ordering': ['ordem'],
            },
        ),
    ]
