# Generated by Django 6.0 on 2026-01-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_diferencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Atuação jurídica com foco...', max_length=200)),
                ('descricao', models.TextField(help_text='Texto explicativo abaixo do título.')),
                ('texto_cta', models.CharField(default='Clique para conhecer cada especialidade', max_length=100)),
                ('texto_botao', models.CharField(default='Ver todas as áreas de atuação', max_length=50)),
                ('link_botao', models.CharField(default='/atuacoes', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home - Seção Atuação',
                'verbose_name_plural': 'Home - Seção Atuação',
            },
        ),
    ]
