# Generated by Django 6.0 on 2026-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homeatuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(help_text='Ex: A DSR por dentro', max_length=100)),
                ('titulo', models.CharField(help_text='Ex: Uma história construída...', max_length=200)),
                ('texto', models.TextField()),
                ('texto_botao', models.CharField(default='Conhecer nossa história', max_length=50)),
                ('link_botao', models.CharField(default='/quem-somos', max_length=200)),
                ('imagem_fundo', models.ImageField(help_text='Imagem de fundo (Ex: Livros). Ideal: Vertical/Quadrada', upload_to='historia/')),
                ('imagem_frente', models.ImageField(help_text='Imagem da frente (Ex: Reunião). Ideal: Horizontal', upload_to='historia/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home - Seção História',
                'verbose_name_plural': 'Home - Seção História',
            },
        ),
    ]
