# Generated by Django 6.0 on 2026-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(help_text='Ex: A DSR por dentro', max_length=100)),
                ('titulo', models.CharField(help_text='Ex: Quem cuida de você...', max_length=200)),
                ('descricao', models.TextField(help_text='Texto alinhado à direita.')),
                ('textura_fundo', models.ImageField(blank=True, help_text='PNG transparente com linhas/formas geométricas. Será aplicada sobre a cor vinho.', null=True, upload_to='home_equipe/')),
                ('texto_botao', models.CharField(default='Conheça a equipe completa', max_length=50)),
                ('link_botao', models.CharField(default='/quem-somos', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home - Seção Equipe',
                'verbose_name_plural': 'Home - Seção Equipe',
            },
        ),
    ]
