# Generated by Django 6.0 on 2026-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_homeequipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(help_text='Ex: Conteúdos e Artigos', max_length=100)),
                ('titulo', models.CharField(help_text='Ex: Entenda seus direitos...', max_length=200)),
                ('descricao', models.TextField(help_text='Texto explicativo.')),
                ('texto_botao', models.CharField(default='Acessar blog', max_length=50)),
                ('link_botao', models.CharField(default='/blog', max_length=200)),
                ('imagem_1', models.ImageField(help_text='Imagem superior esquerda (Ex: Mãos escrevendo)', upload_to='home_blog/')),
                ('imagem_2', models.ImageField(help_text='Imagem inferior direita (Ex: Advogado em pé)', upload_to='home_blog/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home - Seção Blog',
                'verbose_name_plural': 'Home - Seção Blog',
            },
        ),
    ]
