# Generated by Django 6.0 on 2026-01-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_homeblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(help_text='Ex: Entre em contato', max_length=100)),
                ('titulo', models.CharField(help_text='Ex: Precisa de orientação jurídica?', max_length=200)),
                ('descricao', models.TextField(help_text='Texto explicativo sobre o atendimento.')),
                ('texto_whatsapp', models.CharField(default='Falar com a DSR no WhatsApp', max_length=50)),
                ('link_whatsapp', models.CharField(help_text='Link do wpp (https://wa.me/...)', max_length=200)),
                ('texto_botao_form', models.CharField(default='Enviar Formulário', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home - Seção Contato',
                'verbose_name_plural': 'Home - Seção Contato',
            },
        ),
    ]
