# Generated by Django 6.0 on 2026-01-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_homecontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaQuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_topo', models.ImageField(help_text='Banner largo (1920x300px)', upload_to='quem_somos_interna/')),
                ('titulo_principal', models.CharField(max_length=200)),
                ('subtitulo_principal', models.CharField(max_length=200)),
                ('descricao_principal', models.TextField()),
                ('imagem_lateral', models.ImageField(help_text='Imagem que fica ao lado do texto', upload_to='quem_somos_interna/')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('visao', models.TextField(verbose_name='Visão')),
                ('valores', models.TextField(verbose_name='Valores')),
                ('iframe_mapa', models.TextField(help_text='Cole o código <iframe> do Google Maps aqui')),
            ],
            options={
                'verbose_name': 'Página Interna - Quem Somos',
                'verbose_name_plural': 'Página Interna - Quem Somos',
            },
        ),
        migrations.CreateModel(
            name='GaleriaQuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('legenda', models.CharField(blank=True, max_length=100)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='website.paginaquemsomos')),
            ],
        ),
    ]
