# Generated by Django 6.0.1 on 2026-01-28 14:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_paginaquemsomos_galeriaquemsomos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia / Currículo')),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Profissional')),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Conteúdo - Membro da Equipe',
                'verbose_name_plural': 'Conteúdo - Equipe',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
        migrations.AlterModelOptions(
            name='atuacao',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Conteúdo - Atuação', 'verbose_name_plural': 'Conteúdo - Atuações'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publicado_em'], 'verbose_name': 'Conteúdo - Artigo Blog', 'verbose_name_plural': 'Conteúdo - Blog'},
        ),
        migrations.AlterModelOptions(
            name='diferencial',
            options={'ordering': ['ordem'], 'verbose_name': 'Home - Diferencial', 'verbose_name_plural': 'Home - Diferenciais'},
        ),
        migrations.AlterModelOptions(
            name='herohome',
            options={'verbose_name': 'Home - 1. Banner Principal', 'verbose_name_plural': 'Home - 1. Banners Principal'},
        ),
        migrations.AlterModelOptions(
            name='homeatuacao',
            options={'verbose_name': 'Home - Seção Atuação (Texto)', 'verbose_name_plural': 'Home - Seção Atuação (Texto)'},
        ),
        migrations.AlterModelOptions(
            name='homeequipe',
            options={'verbose_name': 'Home - Seção Equipe (Texto)', 'verbose_name_plural': 'Home - Seção Equipe (Texto)'},
        ),
        migrations.AlterModelOptions(
            name='quemsomos',
            options={'verbose_name': 'Home - Seção Quem Somos', 'verbose_name_plural': 'Home - Seção Quem Somos'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='autor',
        ),
        migrations.AddField(
            model_name='atuacao',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Capa da página interna', null=True, upload_to='atuacoes/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='autor_nome',
            field=models.CharField(default='DSR Equipe', max_length=100, verbose_name='Nome do Autor'),
        ),
        migrations.AlterField(
            model_name='atuacao',
            name='conteudo',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Conteúdo completo da página', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo Completo'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='imagem_1',
            field=models.ImageField(help_text='Imagem superior esquerda', upload_to='home_blog/'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='imagem_2',
            field=models.ImageField(help_text='Imagem inferior direita', upload_to='home_blog/'),
        ),
    ]
